apiVersion: v1
kind: Service
metadata:
  name: n8n-service
spec:
  type: ClusterIP
  selector:
    app: n8n   # ⚠️ must match your deployment labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
